# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-22 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bender', '0003_trial_new_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='category',
            field=models.CharField(blank=True, choices=[('descriptive', 'Descriptive parameter'), ('categorical', 'Categorical parameter'), ('uniform', 'Uniformly distributed parameter'), ('normal', 'Normally distributed parameter'), ('lognormal', 'Log-Normally distributed parameter'), ('loguniform', 'Log-Uniformly distributed parameter')], max_length=50, null=True),
        ),
    ]
