# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-07 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bender', '0006_experiment_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='weight',
            field=models.FloatField(default=1),
        ),
    ]
