# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-03-05 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bender', '0007_trial_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tos_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
